define: &exp_name "exp_5 "

train_config:
  epochs: 3000
  batch_size: 20
  model_type: &train_model_type 'CVAE3E3D_RNN' # options CVAE3E1D, CVAE3E3D, CVAE1E1D,  CVAE3E3D_RNN
  lr: 0.0001 #0.0001
  num_workers: 4
  model_save_freq: 200
  data_aug: True

wandb_config:
  wandb_mode: 'disabled'
  wandb_project: 'posefall'
  wandb_exp_name: *exp_name
  wandb_tags: [*train_model_type, 'train']
  wandb_description: "CVAE + RNN: With data aug. Pretrained weights of uestc on Encoder and decoder."

data_config:
  data_path: &data_path "/home/siyuan/research/PoseFall/data/MoCap/Mocap_processed_data"
  pretrained_weights: "/home/siyuan/research/PoseFall/src/model/pretrained_models/uestc/checkpoint_1000.pth.tar" 
  ckpt_path: "/home/siyuan/research/PoseFall/train_exps"


loss_config:
  human_model_loss_weight: 1
  vertex_loss_weight: 1
  kl_loss_weight: 0.00001
  loc_loss_weight: 2
  var_loss_weight: 0.5
  init_pose_loss_weight: 1
  
constant:
  PHASES:
    - 'impa'
    - 'glit'
    - 'fall'
  attributes:
    impact_phase_att: # full list: ["Impact Location", "Impact Attribute", "Impact Force"]
      - "Impact Location"
      - "Impact Attribute"
    glitch_phase_att: # full list: ["Glitch Speed", "Glitch Attribute"]
      - "Glitch Attribute"
    fall_phase_att:  # full list ["Fall Attribute","End Postion"]
      - "Fall Attribute"

  max_frame_dict:
    impa: 100
    glit: 200
    fall: 200

generate_config:
  # 1E1D checkpoint
  # ckpt_path: "/home/siyuan/research/PoseFall/src/wandb/run-20240109_012926-zjoxy2jq/files/2024-01-09_01-29-27_exp_0/epoch_1999.pth"
  # 3E3D checkpoint   
  # ckpt_path: "/home/siyuan/research/PoseFall/src/wandb/run-20240109_192054-obzeak8j/files/2024-01-09_19-20-55_exp_3/epoch_2999.pth"
  ckpt_path: "/home/siyuan/research/PoseFall/train_exps/2024-02-20_01-48-06_exp_4/epoch_2999.pth"
  data_path: *data_path
  output_path: "./gen_results_3E3D_20"
  num_to_gen: 20
  model_type: &eval_model_type 'CVAE3E3D'
  wandb_config:
    wandb_mode: 'disabled'
    wandb_project: 'posefall'
    wandb_exp_name: *exp_name
    wandb_tags: [*eval_model_type, 'eval']
    wandb_description:  "Vanilla CVAE: With no data aug. Pretrained weights of uestc on Encoder and decoder."

recognition_config:
  pretrained_weights: "/home/siyuan/research/PoseFall/src/model/pretrained_models/recognition/uestc_rot6d_stgcn.tar"
  output_path: "./src/evaluate/recognition_ckpts_vanilla"
  batch_size: 16
  lr: 0.00005
  epochs: 2000
  model_save_freq: 500
  evaluation_freq: 200
  wandb_config:
    wandb_mode: 'online'
    wandb_tags: ['recognition', 'train', ]
    wandb_description: "STGCN only"

evaluate_config:
  evaluate_dataset_path: "/home/siyuan/research/PoseFall/gen_results_3E3D_20"
  recognition_model_ckpt_path: "/home/siyuan/research/PoseFall/src/evaluate/recognition_ckpts/recognition_model_2999.pt"
  phase: "glit"
  wandb_config:
    wandb_mode: 'disabled'