define: &exp_name "exp_3"

train_config:
  epochs: 3000
  batch_size: 20
  model_type: &train_model_type 'CVAE3E3D' # options CVAE3E1D, CVAE3E1D
  lr: 0.0001 #0.0001
  num_workers: 4
  model_save_freq: 200
  data_aug: True

wandb_config:
  wandb_mode: 'online'
  wandb_project: 'posefall'
  wandb_exp_name: *exp_name
  wandb_tags: [*train_model_type, 'train']
  wandb_description: "CVAE: With data aug. Pretrained weights of uestc on Encoder and decoder. No armature rotation"

data_config:
  data_path: &data_path "/home/siyuan/research/PoseFall/data/MoCap/Mocap_processed_data"
  pretrained_weights: "/home/siyuan/research/PoseFall/src/model/pretrained_models/uestc/checkpoint_1000.pth.tar" 
  ckpt_path: ""


loss_config:
  human_model_loss_weight: 1
  vertex_loss_weight: 1
  kl_loss_weight: 0.00001
  loc_loss_weight: 1
  var_loss_weight: 0.1

constant:
  PHASES:
    - 'impa'
    - 'glit'
    - 'fall'
  max_frame_dict:
    impa: 100
    glit: 200
    fall: 200

generate_config:
  ckpt_path: "/home/siyuan/research/PoseFall/src/wandb/run-20240109_012926-zjoxy2jq/files/2024-01-09_01-29-27_exp_0/epoch_1999.pth"
  # ckpt_path: "/home/siyuan/research/PoseFall/src/wandb/run-20240109_192054-obzeak8j/files/2024-01-09_19-20-55_exp_3/epoch_2999.pth"
  data_path: *data_path
  output_path: "./gen_results_1E1D_20"
  num_to_gen: 20
  model_type: &eval_model_type 'CVAE1E1D'
  wandb_config:
    wandb_mode: 'disabled'
    wandb_project: 'posefall'
    wandb_exp_name: *exp_name
    wandb_tags: [*eval_model_type, 'eval']
    wandb_description:  "Vanilla CVAE: With no data aug. Pretrained weights of uestc on Encoder and decoder."

recognition_config:
  pretrained_weights: "/home/siyuan/research/PoseFall/src/model/pretrained_models/recognition/uestc_rot6d_stgcn.tar"
  output_path: "./src/evaluate/recognition_ckpts"
  batch_size: 32
  lr: 0.0001
  epochs: 3000
  model_save_freq: 500
  wandb_config:
    wandb_mode: 'online'
    wandb_tags: ['recognition', 'train']

evaluate_config:
  evaluate_dataset_path: "/home/siyuan/research/PoseFall/gen_results_1E1D_20"
  recognition_model_ckpt_path: "/home/siyuan/research/PoseFall/src/evaluate/recognition_ckpts/recognition_model_2999.pt"
  wandb_config:
    wandb_mode: