define: &exp_name "exp_14"

train_config:
  epochs: 2000
  batch_size: 20
  model_type: &train_model_type 'CVAE3E3D_RNN' # options CVAE3E1D, CVAE3E3D, CVAE1E1D,  CVAE3E3D_RNN
  lr: 0.0001 #0.0001
  num_workers: 4
  model_save_freq: 200
  data_aug: True

wandb_config:
  wandb_mode: 'online'
  wandb_project: 'posefall'
  wandb_exp_name: *exp_name
  wandb_tags: [*train_model_type, 'train']
  wandb_description: "CVAE + RNN: feature combineation method: addition. Initial Pose Loss: param + reconstruction. Human Z-axis rotation augmentation added."

data_config:
  data_path: &data_path "/home/siyuan/research/PoseFall/data/MoCap/Mocap_processed_data"
  pretrained_weights: "/home/siyuan/research/PoseFall/src/model/pretrained_models/uestc/checkpoint_1000.pth.tar" 
  ckpt_path: "/home/siyuan/research/PoseFall/train_exps"


loss_config:
  # in-phase loss
  human_model_loss_weight: 1
  vertex_loss_weight: 1
  kl_loss_weight: 0.00001
  # between-phase loss
  loc_loss_weight: 2
  var_loss_weight: 0.5
  # initial pose loss
  init_pose_param_loss_weight: 1
  init_pose_vertex_loss_weight: 2

constant:
  PHASES:
    - 'impa'
    - 'glit'
    - 'fall'
  attributes:
    impact_phase_att: # full list: ["Impact Location", "Impact Attribute", "Impact Force"]
      - "Impact Location"
      - "Impact Attribute"
    glitch_phase_att: # full list: ["Glitch Speed", "Glitch Attribute"]
      - "Glitch Attribute"
    fall_phase_att:  # full list ["Fall Attribute","End Postion"]
      - "Fall Attribute"

  max_frame_dict:
    impa: 100
    glit: 200
    fall: 200

generate_config:
  # 1E1D checkpoint
  ckpt_path: "/home/siyuan/research/PoseFall/src/wandb/run-20240109_012926-zjoxy2jq/files/2024-01-09_01-29-27_exp_0/epoch_1999.pth"
  # 3E3D checkpoint   
  # ckpt_path: "/home/siyuan/research/PoseFall/src/wandb/run-20240109_192054-obzeak8j/files/2024-01-09_19-20-55_exp_3/epoch_2999.pth"
  # ckpt_path: "/home/siyuan/research/PoseFall/train_exps/2024-02-20_01-48-06_exp_4/epoch_2999.pth"
  # exps 6: 3E3D_RNN + init loss (model param only) + addition
  # ckpt_path : "/home/siyuan/research/PoseFall/train_exps/2024-02-24_12-27-03_exp_6/epoch_2999.pth"
  # exps7: 3E3D_RNN + init loss (model param + vertex) + addition
  # ckpt_path : /home/siyuan/research/PoseFall/train_exps/2024-02-25_13-30-02_exp_7/epoch_1999.pth
  # exps8: 3E3D_RNN + init loss (model param + vertex) + addition + increased init pose loss
  # ckpt_path: "/home/siyuan/research/PoseFall/train_exps/2024-02-26_01-00-49_exp_8/epoch_1999.pth"
  # exps 11: 3E3D_RNN + init loss (model param + vertex) + addition + add rotation and trans to the inital pose reconstruction error
  # ckpt_path: "/home/siyuan/research/PoseFall/train_exps/2024-02-27_00-39-56_exp_11/epoch_799.pth"
  # exps 12: 3E3D_RNN + everyting in 11 + add human z-axis rotation augmentation
  # ckpt_path: "/home/siyuan/research/PoseFall/train_exps/2024-02-27_18-55-18_exp_12/epoch_1999.pth"
  # exps 13: 3E3D_RNN + everyting in 12 + add human z-axis rotation augmentation -- official traning weights for 3E3D concate
  # ckpt_path: "/home/siyuan/research/PoseFall/train_exps/2024-02-28_17-47-18_exp_13/epoch_1999.pth"
  # exps 14: 3E3D_RNN + everyting in 13 + add human z-axis rotation augmentation -- official traning weights for 3E3D addition
  ckpt_path: "/home/siyuan/research/PoseFall/train_exps/2024-02-29_23-38-24_exp_14/epoch_1999.pth"
  data_path: *data_path
  output_path: "./gen_results_exp14"
  num_to_gen: 5
  model_type: &eval_model_type 'CVAE3E3D_RNN'
  wandb_config:
    wandb_mode: 'disabled'
    wandb_project: 'posefall'
    wandb_exp_name: *exp_name
    wandb_tags: [*eval_model_type, 'eval']
    wandb_description:  ""

recognition_config:
  pretrained_weights: "/home/siyuan/research/PoseFall/src/model/pretrained_models/recognition/uestc_rot6d_stgcn.tar"
  output_path: "./src/evaluate/recognition_ckpts_vanilla"
  batch_size: 16
  lr: 0.00005
  epochs: 2000
  model_save_freq: 500
  evaluation_freq: 200
  wandb_config:
    wandb_mode: 'online'
    wandb_tags: ['recognition', 'train', ]
    wandb_description: "STGCN only"

evaluate_config:
  evaluate_dataset_path: "/home/siyuan/research/PoseFall/gen_results_3E3D_20"
  recognition_model_ckpt_path: "/home/siyuan/research/PoseFall/src/evaluate/recognition_ckpts/recognition_model_2999.pt"
  phase: "glit"
  wandb_config:
    wandb_mode: 'disabled'