define: &exp_name "exp_2"

train_config:
  epochs: 2000
  batch_size: 20
  model_type: &train_model_type 'CVAE3E1D' # options CVAE3E1D, CVAE3E1D
  lr: 0.0001 #0.0001
  num_workers: 4
  model_save_freq: 200
  data_aug: True

wandb_config:
  wandb_mode: 'online'
  wandb_project: 'posefall'
  wandb_exp_name: *exp_name
  wandb_tags: [*train_model_type, 'train']
  wandb_description: "CVAE: With data aug. Pretrained weights of uestc on Encoder and decoder. No armature rotation"

data_config:
  data_path: &data_path "/home/siyuan/research/PoseFall/data/MoCap/Mocap_processed_data"
  pretrained_weights: "/home/siyuan/research/PoseFall/src/model/pretrained_models/uestc/checkpoint_1000.pth.tar" 
  ckpt_path: ""


loss_config:
  human_model_loss_weight: 1
  vertex_loss_weight: 1
  kl_loss_weight: 0.00001
  loc_loss_weight: 0
  var_loss_weight: 0

constant:
  PHASES:
    - 'impa'
    - 'glit'
    - 'fall'
  max_frame_dict:
    impa: 100
    glit: 200
    fall: 200

eval_config:
  ckpt_path: "/home/siyuan/research/PoseFall/src/wandb/run-20240108_185211-5uckbnfm/files/2024-01-08_18-52-11_exp_0/epoch_199.pth"
  data_path: *data_path
  output_path: "./gen_results"
  num_to_gen: 10
  model_type: &eval_model_type 'CVAE1E1D'
  wandb_config:
    wandb_mode: 'disabled'
    wandb_project: 'posefall'
    wandb_exp_name: *exp_name
    wandb_tags: [*eval_model_type, 'eval']
    wandb_description:  "Vanilla CVAE: With no data aug. Pretrained weights of uestc on Encoder and decoder."