define: &exp_name "exp_5"

rain_hyperparameters:
  epochs: 1000
  batch_size: 8
  model_type: &train_model_type 'CVAE_1D'
  lr: 0.00001
  num_workers: 4
  model_save_freq: 200

wandb_config:
  wandb_mode: 'online'
  wandb_project: 'posefall'
  wandb_exp_name: *exp_name
  wandb_tags: [*train_model_type, 'train']
  wandb_description: "CVAE_1D: With data aug. Pretrained weights on Encoder."

data_config:
  data_path: &data_path "/home/siyuan/research/PoseFall/data/MoCap/Mocap_processed_data" 
  ckpt_path: ""


loss_config:
  human_model_loss_weight: 1
  vertex_loss_weight: 1
  kl_loss_weight: 0.001
  spline_loss_weight: 1
  smoothness_loss_weight: 0.1

constant:
  PHASES:
    - 'impa'
    - 'glit'
    - 'fall'

eval_config:
  ckpt_path: "/home/siyuan/research/PoseFall/src/wandb/run-20231231_151252-qw6flten/files/2023-12-31_15-12-52_exp_5/epoch_999.pth"
  data_path: *data_path
  ouput_path: "./gen_results"
  num_to_gen: 2
  model_type: &eval_model_type 'CVAE_1D'
  wandb_config:
    wandb_mode: 'online'
    wandb_project: 'posefall'
    wandb_exp_name: *exp_name
    wandb_tags: [*eval_model_type, 'eval']
    wandb_description: "CVAE_1D: With data aug. Pretrained weights on Encoder."