define: &exp_name "exp_7"

train_config:
  epochs: 200
  batch_size: 8
  model_type: &train_model_type 'CVAE'
  lr: 0.0001
  num_workers: 4
  model_save_freq: 10
  data_aug: True

wandb_config:
  wandb_mode: 'online'
  wandb_project: 'posefall'
  wandb_exp_name: *exp_name
  wandb_tags: [*train_model_type, 'train', 'data_aug']
  wandb_description: "CVAE: With data aug. Pretrained weights of uestc on Encoder and decoder."

data_config:
  data_path: &data_path "/home/siyuan/research/PoseFall/data/MoCap/Mocap_processed_data"
  pretrained_weights: "/home/siyuan/research/PoseFall/src/model/pretrained_models/uestc/checkpoint_1000.pth.tar" 
  ckpt_path: ""


loss_config:
  human_model_loss_weight: 1
  vertex_loss_weight: 2
  kl_loss_weight: 0.0001
  loc_loss_weight: 0
  var_loss_weight: 0

constant:
  PHASES:
    - 'impa'
    - 'glit'
    - 'fall'

eval_config:
  ckpt_path: "/home/siyuan/research/PoseFall/src/wandb/run-20240102_195306-iw16kkb4/files/2024-01-02_19-53-06_exp_7/epoch_160.pth"
  data_path: *data_path
  output_path: "./gen_results"
  num_to_gen: 50
  model_type: &eval_model_type 'CVAE'
  wandb_config:
    wandb_mode: 'disabled'
    wandb_project: 'posefall'
    wandb_exp_name: *exp_name
    wandb_tags: [*eval_model_type, 'eval']
    wandb_description:  "CVAE: With data aug. Pretrained weights on Encoder and decoder."